# Generated by Django 4.2.10 on 2024-11-26 11:02

import apps.people.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('action_type', models.CharField(choices=[('CHANGE', 'Изменение'), ('DELETE', 'DELETE'), ('ADDING', 'Добавление'), ('RETRY', 'Ретрай')], default='CHANGE', max_length=20, verbose_name='Тип Действия')),
                ('action_description', models.CharField(max_length=255, null=True, verbose_name='Описание действия')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поля')),
                ('field_before', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поле до изменения')),
                ('field_after', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поле после изменения')),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'Список историй изменений',
            },
        ),
        migrations.CreateModel(
            name='BlackListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[apps.people.validators.IinValidator()], verbose_name='ИИН')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('reason', models.CharField(choices=[('AML', 'Член списка ПОДФТ'), ('Other', 'Другая причина')], default='AML', max_length=20, verbose_name='Причина включения в список')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('source', models.PositiveSmallIntegerField(choices=[(0, 'Egov'), (1, 'Добавлен вручную')], default=1, editable=False)),
            ],
            options={
                'verbose_name': 'Член чёрного списка',
                'verbose_name_plural': 'Члены чёрного списка',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('region_id', models.IntegerField(verbose_name='Id региона')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IndividualProprietorList',
            fields=[
                ('iin', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ИИН')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Наименование ИП')),
                ('full_name', models.CharField(max_length=500, null=True, verbose_name='ФИО руководителя')),
                ('kato_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='КАТО')),
                ('date_reg', models.DateField(null=True, verbose_name='Дата регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Синхронизировано')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Индивидуальный Предприниматель',
                'verbose_name_plural': 'Список Индивидуальных Предпринимателей',
                'ordering': ('iin',),
            },
        ),
    ]
