# Generated by Django 4.2.10 on 2024-11-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='uid')),
                ('conversation_id', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], default='SUCCESS', max_length=10, verbose_name='Status')),
                ('iin', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('level', models.CharField(max_length=10, verbose_name='Level')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Time')),
                ('method', models.CharField(db_index=True, max_length=128, verbose_name='Method')),
                ('content', models.TextField(verbose_name='Content')),
                ('token', models.TextField(blank=True, null=True, verbose_name='Token')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Response code')),
                ('runtime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Runtime')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
