# Generated by Django 4.2.10 on 2024-11-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('credits', '0001_initial'),
        ('core', '0001_initial'),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='flow.pipeline', verbose_name='Конвейер'),
        ),
        migrations.AddField(
            model_name='product',
            name='reject_reasons',
            field=models.ManyToManyField(blank=True, to='flow.servicereason', verbose_name='Включить проверки'),
        ),
        migrations.AddField(
            model_name='negativestatus',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_statuses', to='credits.creditapplication'),
        ),
        migrations.AddField(
            model_name='negativestatus',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negative_statuses', to='credits.guarantor'),
        ),
        migrations.AddField(
            model_name='lead',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='people.person', verbose_name='Borrower'),
        ),
        migrations.AddField(
            model_name='lead',
            name='borrower_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='people.personaldata', verbose_name='Анкета заемщика'),
        ),
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='lead',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='credits.channel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='lead',
            name='credit_params',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='credits.creditparams', verbose_name='Параметры кредита'),
        ),
        migrations.AddField(
            model_name='lead',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='credits.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='incomereceipt',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_receipts', to='credits.creditreport'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='credits.creditapplication', verbose_name='Кредит'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guarantor_persons', to='people.person', verbose_name='Физическое лицо гаранта'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='person_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_person_records', to='people.personaldata', verbose_name='Персональные данные гаранта'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_types', to='credits.documentgroup'),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='credit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_report', to='credits.creditapplication', verbose_name='Кредитная заявка'),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='custom_scoring_reason_found',
            field=models.ManyToManyField(blank=True, related_name='+', to='flow.servicereason', verbose_name='Найден в списках ПКБ Custom Scoring'),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='guarantor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_report', to='credits.guarantor', verbose_name='Гарант'),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_report', to='credits.lead', verbose_name='Кредитная заявка'),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='pkb_additional_reason_found',
            field=models.ManyToManyField(blank=True, related_name='+', to='flow.servicereason', verbose_name='Найден в списках ПКБ доп источники'),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='susn_reason_found',
            field=models.ManyToManyField(blank=True, related_name='+', to='flow.servicereason', verbose_name='Найден в списках ПКБ СУСН'),
        ),
        migrations.AddField(
            model_name='credithistory',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_history', to='credits.creditapplication'),
        ),
        migrations.AddField(
            model_name='creditfinance',
            name='credit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_finance', to='credits.creditapplication'),
        ),
        migrations.AddField(
            model_name='creditdocument',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credits.creditapplication'),
        ),
        migrations.AddField(
            model_name='creditdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credits.documenttype', verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='creditdecisionvote',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='credits.creditdecision'),
        ),
    ]
