# Generated by Django 4.2.10 on 2025-03-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_creditapplication_verigram_flow_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditapplicationpayment',
            options={'ordering': ['-created'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddField(
            model_name='creditapplicationpayment',
            name='payment_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные ответа платежной системы'),
        ),
        migrations.AlterField(
            model_name='creditapplicationpayment',
            name='_pay_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='creditapplicationpayment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_payments', to='credits.creditcontract', verbose_name='Кредитный контракт'),
        ),
        migrations.AlterField(
            model_name='creditapplicationpayment',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата контракта из 1С'),
        ),
        migrations.AlterField(
            model_name='creditapplicationpayment',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Идентификатор заказа'),
        ),
        migrations.AlterField(
            model_name='creditapplicationpayment',
            name='status',
            field=models.CharField(choices=[('NOT_PAID', 'Не Оплачено'), ('PAID', 'Оплачено'), ('CANCELED', 'Отменен при оплате'), ('PAYMENT_ERROR', 'Ошибка оплаты'), ('IN_PROGRESS', 'В процессе'), ('WAITING', 'В ожидании')], db_index=True, default='NOT_PAID', max_length=50, verbose_name='Статус'),
        ),
    ]
