# Generated by Django 4.2.10 on 2024-11-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('people', '0001_initial'),
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonalrecord',
            name='additional_contacts',
            field=models.ManyToManyField(blank=True, through='people.AdditionalContactRelation', to='people.personcontact', verbose_name='Дополнительные контакты'),
        ),
        migrations.AddField(
            model_name='profilepersonalrecord',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank'),
        ),
        migrations.AddField(
            model_name='profilepersonalrecord',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_record', to='accounts.profile', verbose_name='Пользователь ЛК'),
        ),
        migrations.AddField(
            model_name='profilepersonalrecord',
            name='real_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_real_related', to='people.address', verbose_name='Фактический адрес проживания'),
        ),
        migrations.AddField(
            model_name='profilepersonalrecord',
            name='reg_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reg_related', to='people.address', verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this profile belongs to. A profile will get all permissions granted to each of their groups.', related_name='profile_set', related_query_name='profile', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profile',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_account', to='people.person', verbose_name='Заёмщик'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this profile.', related_name='profile_set', related_query_name='profile', to='auth.permission', verbose_name='profile permissions'),
        ),
    ]
