# Generated by Django 4.2.10 on 2024-12-10 11:16

import apps.people.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonalrecord',
            name='spouse_iin',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[apps.people.validators.IinValidator], verbose_name='ИИН Супруги/а'),
        ),
    ]
