# Generated by Django 4.2.10 on 2024-12-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profilepersonalrecord_spouse_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonalrecord',
            name='document_exp_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия документа'),
        ),
        migrations.AlterField(
            model_name='profilepersonalrecord',
            name='document_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи документа'),
        ),
    ]
