# Generated by Django 4.2.10 on 2025-01-08 08:17

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profilepersonalrecord_document_exp_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='Номер карты')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('card_holder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Держатель карты')),
                ('card_type', models.CharField(blank=True, choices=[('VISA', 'VISA'), ('MASTERCARD', 'MasterCard')], max_length=10, null=True, verbose_name='Тип карты')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to='accounts.profilepersonalrecord', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN номер')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.profilepersonalrecord', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Банковский счет',
                'verbose_name_plural': 'Банковские счета',
                'ordering': ['-created'],
            },
        ),
    ]
