# Generated by Django 4.2.10 on 2025-03-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profilepersonalrecord_average_monthly_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonalrecord',
            name='bank_statement_card_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Последние 4 цифры карты из выписки'),
        ),
    ]
