# Generated by Django 4.2.10 on 2024-11-26 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('recipients', models.CharField(editable=False, max_length=255, verbose_name='Получатели')),
                ('content', models.TextField(editable=False, verbose_name='Содержимое')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификатор в СМС сервисе')),
                ('error_code', models.IntegerField(editable=False, null=True, verbose_name='Код ошибки')),
                ('error_description', models.CharField(editable=False, max_length=255, null=True, verbose_name='Описание ошибки')),
            ],
            options={
                'verbose_name': 'SMS сообщение',
                'verbose_name_plural': 'SMS сообщения',
            },
        ),
        migrations.CreateModel(
            name='SMSType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Уникальный код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип сообщения',
                'verbose_name_plural': 'Типы сообщений',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Используется django.template', verbose_name='Содержимое')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.smstype')),
            ],
            options={
                'verbose_name': 'Шаблон СМС',
                'verbose_name_plural': 'Шаблоны СМС',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, editable=False, max_length=12, verbose_name='OTP')),
                ('verified', models.BooleanField(default=False, editable=False, verbose_name='Подтверждён')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(editable=False, max_length=128, region=None, verbose_name='Мобильный телефон')),
                ('failed_verification_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Неудачное количество попыток')),
            ],
            options={
                'verbose_name': 'Одноразовый пароль',
                'verbose_name_plural': 'Одноразовые пароли',
                'unique_together': {('code', 'mobile_phone')},
            },
        ),
    ]
